CREATE TABLE `lds_user_job` (
  `id_key` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `job_id` CHAR(50) NOT NULL COMMENT '职位Id',
  `job` CHAR(50) NOT NULL COMMENT '职位名称',
  `job_contain` CHAR(50) DEFAULT NULL COMMENT '职位包含的字符串',
  `created_by` CHAR(10) DEFAULT NULL COMMENT '创建人',
  `updated_by` CHAR(10) DEFAULT NULL COMMENT '更新人',
  `created_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `updated_date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '更新时间',
  PRIMARY KEY (`id_key`),
  UNIQUE KEY `UQINDX_LDS_USER_JOB_0` (`job_id`),
  UNIQUE KEY `UQINDX_LDS_USER_JOB_1` (`job`)
  ) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='职位表';